# -*- mode: ruby -*-
# vi: set ft=ruby :

# -------------------------------------------------------------------
# Configuration options
# -------------------------------------------------------------------
NUM_OF_MANAGERS=1
NUM_OF_WORKERS=1
SIZE = 1024
NUM_CPUS = 2
# -------------------------------------------------------------------
# (End configuration options)

# -- Internal variables
VAGRANTFILE_API_VERSION = "2"

@initManager = <<EOD
echo initManager Arguments: $*
local currManager=$3
# Todo: We have an issue here, if re-creating the machines, then the old token will be re-used, which is wrong ...
if [ ! -d "/vagrant/.vagrant/swarm-token" ]; then
    mkdir /vagrant/.vagrant/swarm-token
    chmod 777 /vagrant/.vagrant/swarm-token

    docker swarm init --advertise-addr eth1:2377
    docker swarm join-token -q manager > /vagrant/.vagrant/swarm-token/manager
    docker swarm join-token -q worker > /vagrant/.vagrant/swarm-token/worker
else
    docker swarm join \
      --token `cat /vagrant/.vagrant/swarm-token/manager` \
      192.168.50.100:2377
fi
EOD

@initWorker = <<EOD
docker swarm join \
  --token `cat  /vagrant/.vagrant/swarm-token/worker` \
  192.168.50.100:2377
EOD


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


end
