# -*- mode: ruby -*-
# vi: set ft=ruby :

# -------------------------------------------------------------------
# Configuration options
# -------------------------------------------------------------------
NUM_OF_MANAGERS=1
NUM_OF_WORKERS=1
SIZE = 1024
NUM_CPUS = 2
# -------------------------------------------------------------------
# (End configuration options)

# -- Internal variables
VAGRANTFILE_API_VERSION = "2"

@initManager = <<EOD
echo initManager Arguments: $*
local currManager=$3
# Todo: We have an issue here, if re-creating the machines, then the old token will be re-used, which is wrong ...
if [ ! -d "/vagrant/.vagrant/swarm-token" ]; then
    mkdir /vagrant/.vagrant/swarm-token
    chmod 777 /vagrant/.vagrant/swarm-token

    docker swarm init --advertise-addr eth1:2377
    docker swarm join-token -q manager > /vagrant/.vagrant/swarm-token/manager
    docker swarm join-token -q worker > /vagrant/.vagrant/swarm-token/worker
else
    docker swarm join \
      --token `cat /vagrant/.vagrant/swarm-token/manager` \
      192.168.50.100:2377
fi
EOD

@initWorker = <<EOD
docker swarm join \
  --token `cat  /vagrant/.vagrant/swarm-token/worker` \
  192.168.50.100:2377
EOD

@deploySwarm = <<EOD

docker-machine scp ./docker-stack.yml manager-1:/home/docker/docker-stack.yml;
docker-machine ssh manager-1 cd /home/docker;
docker-machine ssh manager-1 docker stack deploy --compose-file docker-stack.yml vote;

EOD


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider 'virtualbox' do |v|
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

  config.ssh.insert_key = false

  (1..NUM_OF_MANAGERS).each do |mgrNumber|
    config.vm.define "manager-#{mgrNumber}" do |node|
      node.vm.hostname = "manager-#{mgrNumber}"
      node.vm.network "private_network", ip: "192.168.50.#{99+mgrNumber}"
      node.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
      end
      #node.vm.provision "shell", inline: "sudo apt-get update"
      node.vm.provision "docker"
      node.vm.provision "shell", inline: @initManager, args: [ "#{NUM_OF_MANAGERS}" , "192.168.50.#{99+mgrNumber}", "#{mgrNumber}" ]
    end
  end

  (1..NUM_OF_WORKERS).each do |workerNumber|
    config.vm.define "worker-#{workerNumber}" do |node|
      node.vm.hostname = "worker-#{workerNumber}"
      node.vm.network "private_network", ip: "192.168.50.#{149+workerNumber}"
      node.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
      end
      #node.vm.provision "shell", inline: "sudo apt-get update"
      node.vm.provision "docker"
      node.vm.provision "shell", inline: @initWorker
    end
  end

  #machine-1.vm.provision "shell", inline: $deploySwarm

end
